name: flossy
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  uuid: ^4.5.1
  intl: ^0.20.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13



flutter:


  uses-material-design: true
